export const COMPANY_GETLIST_SUCCESS     = 'COMPANY_GETLIST_SUCCESS'
export const COMPANY_GETLIST_FAILURE     = 'COMPANY_GETLIST_FAILURE'

export const COMPANY_NEW_ISSAVING  = 'COMPANY_NEW_ISSAVING'
export const COMPANY_NEW_SUCCESS   = 'COMPANY_NEW_SUCCESS'
export const COMPANY_NEW_FAILURE   = 'COMPANY_NEW_FAILURE'

export const COMPANY_ISFETCHING      = 'COMPANY_ISFETCHING'
export const COMPANY_FETCH_SUCCESS   = 'COMPANY_FETCH_SUCCESS'
export const COMPANY_FETCH_FAILURE   = 'COMPANY_FETCH_FAILURE'

export const COMPANY_FETCHDETAILS_SUCCESS   = 'COMPANY_FETCHDETAILS_SUCCESS'
export const COMPANY_FETCHDETAILS_FAILURE   = 'COMPANY_FETCHDETAILS_FAILURE'

export const COMPANY_IS_UPDATING             = 'COMPANY_IS_UPDATING'
export const COMPANY_UPDATEDETAILS_SUCCESS   = 'COMPANY_UPDATEDETAILS_SUCCESS'
export const COMPANY_UPDATEDETAILS_FAILURE   = 'COMPANY_UPDATEDETAILS_FAILURE'

export const COMPANY_ISADDING_BENEFICIAL        = 'COMPANY_ISADDING_BENEFICIAL'
export const COMPANY_ADDINGBENEFICIAL_SUCCESS   = 'COMPANY_ADDINGBENEFICIAL_SUCCESS'
export const COMPANY_ADDINGBENEFICIAL_FAILURE   = 'COMPANY_ADDINGBENEFICIAL_FAILURE'