export const COMPANY_GETLIST_ISFETCHING  = 'COMPANY_GETLIST_ISFETCHING'
export const COMPANY_GETLIST_SUCCESS     = 'COMPANY_GETLIST_SUCCESS'
export const COMPANY_GETLIST_FAILURE     = 'COMPANY_GETLIST_FAILURE'
