export const COMPANY_GETLIST_SUCCESS     = 'COMPANY_GETLIST_SUCCESS'
export const COMPANY_GETLIST_FAILURE     = 'COMPANY_GETLIST_FAILURE'

export const COMPANY_NEW_ISSAVING  = 'COMPANY_NEW_ISSAVING'
export const COMPANY_NEW_SUCCESS   = 'COMPANY_NEW_SUCCESS'
export const COMPANY_NEW_FAILURE   = 'COMPANY_NEW_FAILURE'